# Server
server:
    port: 8082

# Spring
spring:
    application:
        name: producao
    profiles:
        active: dev
    flyway:
        enabled: true
    jpa:
        hibernate:
            ddl-auto: none
